// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PAnswerProblem: typeof import('./src/components/problems/PAnswerProblem.vue')['default']
    PBlank: typeof import('./src/components/content/PBlank.vue')['default']
    PBlankProblem: typeof import('./src/components/problems/PBlankProblem.vue')['default']
    PChoice: typeof import('./src/components/problem/PChoice.vue')['default']
    PChoiceProblem: typeof import('./src/components/problems/PChoiceProblem.vue')['default']
    PContent: typeof import('./src/components/content/PContent.vue')['default']
    PDisplayProblem: typeof import('./src/components/problems/PDisplayProblem.vue')['default']
    PImage: typeof import('./src/components/content/PImage.vue')['default']
    PJudgeProblem: typeof import('./src/components/problems/PJudgeProblem.vue')['default']
    PLatex: typeof import('./src/components/content/PLatex.vue')['default']
    PProblem: typeof import('./src/components/problems/PProblem.vue')['default']
    PSubProblem: typeof import('./src/components/problems/PSubProblem.vue')['default']
    PTable: typeof import('./src/components/content/PTable.vue')['default']
    PText: typeof import('./src/components/content/PText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
