/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PAnswerProblem: typeof import('./src/components/problems/PAnswerProblem.vue')['default']
    PBlank: typeof import('./src/components/content/PBlank.vue')['default']
    PBlankProblem: typeof import('./src/components/problems/PBlankProblem.vue')['default']
    PChoiceProblem: typeof import('./src/components/problems/PChoiceProblem.vue')['default']
    PContent: typeof import('./src/components/content/PContent.vue')['default']
    PContentEditor: typeof import('./src/components/content/PContentEditor.vue')['default']
    PCreateProblem: typeof import('./src/components/problems/PCreateProblem.vue')['default']
    PCreateProblemGroup: typeof import('./src/components/problem-group/PCreateProblemGroup.vue')['default']
    PDisplayProblem: typeof import('./src/components/problems/PDisplayProblem.vue')['default']
    PDisplayProblemGroup: typeof import('./src/components/problem-group/PDisplayProblemGroup.vue')['default']
    PFormulaEdit: typeof import('./src/components/content/PFormulaEdit.vue')['default']
    PImage: typeof import('./src/components/content/PImage.vue')['default']
    PImg: typeof import('./src/components/content/PImg.vue')['default']
    PLatex: typeof import('./src/components/content/PLatex.vue')['default']
    PMaterial: typeof import('./src/components/content/PMaterial.vue')['default']
    PMaterialEdit: typeof import('./src/components/content/PMaterialEdit.vue')['default']
    PPaper: typeof import('./src/components/paper/PPaper.vue')['default']
    PPaperElement: typeof import('./src/components/paper/PPaperElement.vue')['default']
    PParagraph: typeof import('./src/components/content/PParagraph.vue')['default']
    PProblem: typeof import('./src/components/problems/PProblem.vue')['default']
    PProblemGroup: typeof import('./src/components/problem-group/PProblemGroup.vue')['default']
    PSubProblem: typeof import('./src/components/problems/PSubProblem.vue')['default']
    PTable: typeof import('./src/components/content/PTable.vue')['default']
    PText: typeof import('./src/components/content/PText.vue')['default']
    PTextarea: typeof import('./src/components/content/PTextarea.vue')['default']
    PTextEdit: typeof import('./src/components/content/PTextEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
